#!/bin/bash
# Generated by gopher-pipelines version 0.0.0
# Generated at 2018-08-28 17:23:41
user_name="$(id -u -n)"
user_email="${user_name}@umn.edu"
single_id=$(qsub -q mesabi -m abe -M "${user_email}" -l "mem=12000mb,nodes=1:ppn=4,walltime=7200" -t 1-5 -v "SampleSheet=/panfs/roc/scratch/konox006/2018-08-28.bulk_rnaseq/2018-08-28.konox006.bulk_rnaseq.samplesheet.txt,PURGE=false" /panfs/roc/groups/14/msistaff/konox006/Soft/gopher-pipeline-refactor/PBS/bulk_rnaseq_single_sample.pbs)
summary_id=$(qsub -q mesabi -m abe -M "${user_email}" -W "depend=afterokarray:${single_id}" -v "base_in=/panfs/roc/scratch/konox006/2018-08-28.bulk_rnaseq/2018-08-28.konox006.bulk_rnaseq.samplesheet.txt" /panfs/roc/groups/14/msistaff/konox006/Soft/gopher-pipeline-refactor/PBS/run_summary_stats.pbs)
echo "Emails will be sent to ${user_email}"
echo "Single samples job array ID: ${single_id}"
echo "Summary job ID: ${summary_id}"
