#!/bin/bash
# Generated by gopher-pipelines version 0.0.0
# Generated at 2018-08-28 10:04:47
single_id=$(qsub -q mesabi -l "mem=12000mb,nodes=1:ppn=6,walltime=43200" -t 1-5 -v "SampleSheet=/panfs/roc/scratch/konox006/2018-08-28.bulk_rnaseq/2018-08-28.konox006.bulk_rnaseq.samplesheet.txt,PURGE=false" /panfs/roc/groups/14/msistaff/konox006/Soft/gopher-pipeline-refactor/PBS/bulk_rnaseq_single_sample.pbs)
summary_id=$(qsub -q mesabi -W depend=afterok:${single_id} -v "base_in=/panfs/roc/scratch/konox006/2018-08-28.bulk_rnaseq/2018-08-28.konox006.bulk_rnaseq.samplesheet.txt" /panfs/roc/groups/14/msistaff/konox006/Soft/gopher-pipeline-refactor/PBS/run_summary_stats.pbs)
echo "Single samples job array ID: ${single_id}"
echo "Summary job ID: ${summary_id}"
