#!/bin/bash
# Generated by gopher-pipelines version 0.0
# Generated at 2018-08-20 17:01:41
# Software versions
# HISAT2: 2.1.0
# FASTQC: 0.11.7
# TRIMMOMATIC: 0.33
# JAVA: jdk1.8.0_144
# SAMTOOLS: 1.7
# R: 3.5.0
single_id=$(qsub -q mesabi -l "mem=12000mb,nodes=1:ppn=6,walltime=43200" -t 1-6 -v "SampleSheet=Test_Data/Output_Dir/2018-08-20.tomkono.bulk_rnaseq.samplesheet.txt,overwrite=0" /Users/tomkono/Dropbox/GitHub/RIS/gopher-pipeline-refactor/PBS/bulk_rnaseq_single_sample.pbs)
summary_id=$(qsub -q mesabi -W depend=afterok:${single_id} -v "base_in=Test_Data/Output_Dir/2018-08-20.tomkono.bulk_rnaseq.samplesheet.txt" /Users/tomkono/Dropbox/GitHub/RIS/gopher-pipeline-refactor/PBS/run_summary_stats.pbs)
